#!/bin/sh
#
# @name Lumenier QAV-R (raceblade) 5" arms
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
#
# @maintainer James Goppert <james.goppert@gmail.com>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

param import-as-default /etc/init.d/4003.params
