#!/bin/sh
#
# @name 3DR Solo
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board intel_aerofc-v1 exclude
#
# @maintainer Andreas Antener <andreas@uaventure.com>
#

sh /etc/init.d/rc.mc_defaults

param import-as-default /etc/init.d/4030.params
set MIXER quad_x

set PWM_OUT 1234
set MIXER_AUX none

