#!/bin/sh
#
# @name Reaper 500 Quad
#
# @board px4_fmu-v2 exclude
#
# @type Quadrotor H
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @maintainer Blankered
#

sh /etc/init.d/rc.mc_defaults

param import-as-default /etc/init.d/4040.params

set MIXER quad_h

set PWM_OUT 1234

set MIXER_AUX pass

set PWM_AUX_OUT 1234
