#!/bin/sh
#
# @name HolyBro QAV250
#
# @board px4_fmu-v2 exclude
# @url https://docs.px4.io/en/frames_multicopter/holybro_qav250_pixhawk4_mini.html
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Beat Kueng <beat-kueng@gmx.net>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234


param import-as-default /etc/init.d/4052.params
