#!/bin/sh
#
# @name ZMR250 Racer
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
#
# @maintainer Anton Matosov <anton.matosov@gmail.com>
#

sh /etc/init.d/rc.mc_defaults

set MIXER zmr250
set PWM_OUT 1234

param import-as-default /etc/init.d/4080.params
